=== GrieverGF/hunter-on-sky/misp/web/app/files/misp-galaxy/schema_galaxies.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-galaxies - Galaxies",
  "id": "https://www.github.com/MISP/misp-galaxies/schema_galaxies.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "description": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "icon": {
      "type": "string"
    },
    "uuid": {
      "type": "string"
    },
    "namespace": {
      "type": "string"
    },
    "kill_chain_order": {
      "type": "object"
    }
  },
  "required": [
    "description",
    "type",
    "version",
    "name",
    "uuid"
  ]
}

=== GrieverGF/hunter-on-sky/misp/web/app/files/misp-galaxy/galaxies/tea-matrix.json
{
  "description": "Tea Matrix",
  "icon": "map",
  "kill_chain_order": {
    "tea": [
      "black",
      "blend",
      "green",
      "white",
      "yellow",
      "oolong",
      "post-fermented"
    ]
  },
  "name": "Tea Matrix",
  "namespace": "tea-matrix",
  "type": "tea-matrix",
  "uuid": "c5f2dfb4-21a1-42d8-a452-1d3c36a204ff",
  "version": 1
}

=== GrieverGF/hunter-on-sky/misp/web/app/files/misp-galaxy/galaxies/attck4fraud.json
{
  "description": "attck4fraud - Principles of MITRE ATT&CK in the fraud domain",
  "icon": "map",
  "kill_chain_order": {
    "fraud-tactics": [
      "Initiation",
      "Target Compromise",
      "Perform Fraud",
      "Obtain Fraudulent Assets",
      "Assets Transfer",
      "Monetisation"
    ]
  },
  "name": "attck4fraud",
  "namespace": "misp",
  "type": "financial-fraud",
  "uuid": "cc0c8ae9-aec2-42c6-9939-f4f82b051836",
  "version": 1
}

=== GrieverGF/hunter-on-sky/misp/web/app/files/misp-galaxy/galaxies/mitre-attack-pattern.json
{
  "description": "ATT&CK Tactic",
  "icon": "map",
  "kill_chain_order": {
    "mitre-attack": [
      "initial-access",
      "execution",
      "persistence",
      "privilege-escalation",
      "defense-evasion",
      "credential-access",
      "discovery",
      "lateral-movement",
      "collection",
      "command-and-control",
      "exfiltration",
      "impact"
    ],
    "mitre-mobile-attack": [
      "initial-access",
      "persistence",
      "privilege-escalation",
      "defense-evasion",
      "credential-access",
      "discovery",
      "lateral-movement",
      "effects",
      "collection",
      "exfiltration",
      "command-and-control",
      "network-effects",
      "remote-service-effects"
    ],
    "mitre-pre-attack": [
      "priority-definition-planning",
      "priority-definition-direction",
      "target-selection",
      "technical-information-gathering",
      "people-information-gathering",
      "organizational-information-gathering",
      "technical-weakness-identification",
      "people-weakness-identification",
      "organizational-weakness-identification",
      "adversary-opsec",
      "establish-&-maintain-infrastructure",
      "persona-development",
      "build-capabilities",
      "test-capabilities",
      "stage-capabilities"
    ]
  },
  "name": "Attack Pattern",
  "namespace": "mitre-attack",
  "type": "mitre-attack-pattern",
  "uuid": "c4e851fa-775f-11e7-8163-b774922098cd",
  "version": 8
}

=== GrieverGF/hunter-on-sky/misp/web/app/files/misp-galaxy/galaxies/sod-matrix.json
{
  "description": "SoD Matrix",
  "icon": "map",
  "kill_chain_order": {
    "during-incident-crime": [
      "CSIRT",
      "LEA",
      "Judiciary",
      "Prosecutors"
    ],
    "post-incident-crime": [
      "CSIRT",
      "LEA",
      "Judiciary",
      "Prosecutors"
    ],
    "prior-to-incident-crime": [
      "CSIRT",
      "LEA",
      "Judiciary",
      "Prosecutors"
    ]
  },
  "name": "SoD Matrix",
  "namespace": "sod-matrix",
  "type": "sod-matrix",
  "uuid": "50104ead-7315-457c-b596-b4471cabf28b",
  "version": 1
}

=== GrieverGF/hunter-on-sky/misp/web/app/files/misp-galaxy/galaxies/threat-actor.json
{
  "description": "Threat actors are characteristics of malicious actors (or adversaries) representing a cyber attack threat including presumed intent and historically observed behaviour.",
  "icon": "user-secret",
  "name": "Threat Actor",
  "namespace": "misp",
  "type": "threat-actor",
  "uuid": "698774c7-8022-42c4-917f-8d6e4f06ada3",
  "version": 3
}

=== GrieverGF/hunter-on-sky/misp/web/app/files/misp-galaxy/galaxies/rat.json
{
  "description": "remote administration tool or remote access tool (RAT), also called sometimes remote access trojan, is a piece of software or programming that allows a remote \"operator\" to control a system as if they have physical access to that system.",
  "icon": "eye",
  "name": "RAT",
  "namespace": "misp",
  "type": "rat",
  "uuid": "06825db6-4797-11e7-ac4d-af25fdcdd299",
  "version": 3
}

=== GrieverGF/hunter-on-sky/misp/web/app/files/misp-galaxy/galaxies/preventive-measure.json
{
  "description": "Preventive measures based on the ransomware document overview as published in https://docs.google.com/spreadsheets/d/1TWS238xacAto-fLKh1n5uTsdijWdCEsGIM0Y0Hvmc5g/pubhtml# . The preventive measures are quite generic and can fit any standard Windows infrastructure and their security measures.",
  "icon": "shield",
  "name": "Preventive Measure",
  "namespace": "misp",
  "type": "preventive-measure",
  "uuid": "8168995b-adcd-4684-9e37-206c5771505a",
  "version": 3
}

=== GrieverGF/hunter-on-sky/misp/web/app/files/misp-galaxy/galaxies/exploit-kit.json
{
  "description": "Exploit-Kit is an enumeration of some exploitation kits used by adversaries. The list includes document, browser and router exploit kits.It's not meant to be totally exhaustive but aim at covering the most seen in the past 5 years",
  "icon": "internet-explorer",
  "name": "Exploit-Kit",
  "namespace": "misp",
  "type": "exploit-kit",
  "uuid": "6ab240ec-bd79-11e6-a4a6-cec0c932ce01",
  "version": 4
}
