=== GrieverGF/hunter-on-sky/misp/web/app/files/misp-galaxy/schema_misp.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-galaxies - MISP",
  "id": "https://www.github.com/MISP/misp-galaxies/schema_misp.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "elements_url": {
      "type": "string"
    },
    "default_predicate_value_in": {
      "type": "string"
    },
    "default_predicate_value": {
      "type": "string"
    },
    "cluster_url": {
      "type": "string"
    },
    "predicate_in": {
      "type": "string"
    }
  },
  "required": [
    "elements_url",
    "default_predicate_value_in",
    "default_predicate_value",
    "cluster_url",
    "predicate_in"
  ]
}

=== GrieverGF/hunter-on-sky/misp/web/app/files/misp-galaxy/misp/threat-actor.json
{
  "elements_url": "https://raw.githubusercontent.com/MISP/misp-galaxy/master/elements/",
  "default_predicate_value_in": "values",
  "default_predicate_value": "value",
  "cluster_url": "https://raw.githubusercontent.com/MISP/misp-galaxy/master/cluster/threat-actor.json",
  "predicate_in": "elementOneOf"
}
